timeout for functions that use udp
PassTheMayo/minecraft-server-util pull request #51
Opened 2021-07-20 00:28 UTC by misimisi171718

Added a time to the UDPsocket class this should solve issue #38 without any memory leaks

2021-08-12 06:14 UTC, PassTheMayo requested changes
This PR looks good except for a minor linting rule violation. Once this is fixed, I will accept the PR.

2021-08-12 06:14 UTC, PassTheMayo commented on src/structure/UDPSocket.ts
> +			if(this.timeout != 0)
Spacing, comparison operators, and bracket placement should follow linting rules

2021-08-12 14:36 UTC, misimisi171718 commented
I fixed the linting issue it should be good to merge

2021-08-13 19:21 UTC, PassTheMayo commented
I had actually already implemented a timeout for UDP methods in my working copy for the latest `3.6.0` release which uses a `TimeoutPromise` utility class that was used previously. I am gonna go ahead and close this for now.

2021-08-13 19:21 UTC, closed without merging